#!/bin/bash

export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"

export COLOR=0x40ffffff
export BORDER_COLOR=0x30ffffff
export BORDER_WIDTH=2
export HEIGHT=30
export RADIUS=20

config=(
  height=40
  position=top
  color=0x00000000
  y_offset=0
  blur_radius=20
)
sketchybar --bar "${config[@]}"

config=(
  drawing=on
  updates=on
  label.font="SF Pro:Semibold:13"
  icon.font="SF Symbols:Bold:15"
  padding_left=0
  padding_right=0
)
sketchybar --default "${config[@]}"

$ITEM_DIR/clock.sh
$ITEM_DIR/aerospace.sh
# $ITEM_DIR/hide_on_hover.sh

# config=(
#     background.color=$COLOR
#     background.height=$HEIGHT
#     background.corner_radius=$RADIUS
#     background.border_width=$BORDER_WIDTH
#     background.border_color=$BORDER_COLOR
#     blur_radius=4
# )
# sketchybar --add bracket rightSide clock --set rightSide "${config[@]}"

sketchybar --update
